language: node_js
node_js:
  - "6"
services:
  - mongodb
before_install:
  - npm i -g npm@5
after_script:
  - npm run codecov
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
env:
  - CXX=g++-4.8
