language: node_js
node_js:
  - "6.2"
services:
  - mongodb
after_script:
  - npm run report-coverage
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
env:
  - CXX=g++-4.8
